ALTER TABLE products
  ADD COLUMN IF NOT EXISTS price_submission_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_price_submitted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_price_approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS price_version INTEGER NOT NULL DEFAULT 0;
