import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bell,
  Box,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Eye,
  EyeOff,
  FileCheck,
  FileText,
  FolderTree,
  Globe,
  Headphones,
  History,
  Home,
  Image,
  KeyRound,
  LayoutDashboard,
  LineChart,
  List,
  Lock,
  Mail,
  MapPin,
  Package,
  Palette,
  RefreshCw,
  RotateCcw,
  Ruler,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Star,
  Store,
  Truck,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  XCircle,
} from "lucide-react";
import type { AdminPageId, AdminPageMeta, AdminTabConfig } from "./types";

function tabs(...items: AdminTabConfig[]): AdminTabConfig[] {
  return items;
}

export const PAGE_TABS: Record<AdminPageId, AdminTabConfig[]> = {
  dashboard: tabs(
    { id: "overview", label: "Overview", icon: LayoutDashboard },
    { id: "sales", label: "Sales", icon: DollarSign },
    { id: "orders", label: "Orders", icon: ShoppingCart },
    { id: "customers", label: "Customers", icon: UserRound },
    { id: "products", label: "Products", icon: Package },
    { id: "payments", label: "Payments", icon: CreditCard },
    { id: "delivery", label: "Delivery", icon: Truck },
    { id: "alerts", label: "Alerts", icon: Bell },
  ),
  employees: tabs(
    { id: "all", label: "All Employees", icon: UsersRound },
    { id: "active", label: "Active", icon: UserCheck },
    { id: "inactive", label: "Inactive", icon: UserRound },
    { id: "unassigned", label: "Unassigned Role", icon: Shield },
    { id: "new", label: "New Employees", icon: UserPlus },
    { id: "performance", label: "Performance", icon: LineChart },
    { id: "activity", label: "Activity", icon: Activity },
  ),
  customers: tabs(
    { id: "all", label: "All Customers", icon: Users },
    { id: "active", label: "Active", icon: UserCheck },
    { id: "inactive", label: "Inactive", icon: UserRound },
    { id: "new", label: "New Customers", icon: UserPlus },
    { id: "top", label: "Top Customers", icon: Star },
  ),
  roles: tabs(
    { id: "roles", label: "Roles", icon: Shield },
    { id: "permissions", label: "Permissions", icon: KeyRound },
    { id: "admins", label: "Admin Users", icon: ShieldCheck },
    { id: "access", label: "Access Control", icon: Lock },
    { id: "security", label: "Security Logs", icon: ScrollText },
  ),
  products: tabs(
    { id: "all", label: "All Clothes", icon: Package },
    { id: "active", label: "Active Clothes", icon: CheckCircle2 },
    { id: "draft", label: "Draft Clothes", icon: FileText },
    { id: "low-stock", label: "Low Stock Clothes", icon: AlertTriangle, accent: "yellow" },
    { id: "out-of-stock", label: "Out of Stock", icon: XCircle, accent: "red" },
    { id: "best-selling", label: "Best Selling", icon: Star },
    { id: "categories", label: "Clothing Categories", icon: FolderTree },
    { id: "variants", label: "Size / Color Variants", icon: Palette },
    { id: "images", label: "Product Images", icon: Image },
    { id: "featured", label: "Featured Clothes", icon: Star },
  ),
  sections: tabs(
    { id: "all", label: "All Sections", icon: List },
    { id: "active", label: "Active Sections", icon: Eye },
    { id: "hidden", label: "Hidden Sections", icon: EyeOff },
    { id: "homepage", label: "Homepage Sections", icon: Home },
    { id: "categories", label: "Clothing Categories", icon: FolderTree },
    { id: "collections", label: "Collection Sections", icon: Box },
    { id: "menu", label: "Menu Sections", icon: LayoutDashboard },
  ),
  orders: tabs(
    { id: "all", label: "All Orders", icon: ClipboardList },
    { id: "new", label: "New Orders", icon: ShoppingCart },
    { id: "pending", label: "Pending Orders", icon: Clock },
    { id: "processing", label: "Processing", icon: RefreshCw },
    { id: "tailoring", label: "Tailoring / Measurement", icon: Ruler },
    { id: "ready", label: "Ready for Delivery", icon: Package },
    { id: "delivered", label: "Delivered", icon: CheckCircle2 },
    { id: "cancelled", label: "Cancelled", icon: XCircle },
    { id: "returned", label: "Returned", icon: RotateCcw },
    { id: "custom", label: "Custom Clothing Orders", icon: Ruler },
  ),
  payments: tabs(
    { id: "overview", label: "Overview", icon: LayoutDashboard, accent: "blue" },
    { id: "all", label: "All Payments", icon: Wallet, accent: "blue" },
    { id: "stripe", label: "Stripe Payments", icon: CreditCard, accent: "purple" },
    { id: "bank", label: "Bank Transfer / QR", icon: Banknote, accent: "green" },
    { id: "pending", label: "Pending Verification", icon: Clock, accent: "yellow" },
    { id: "failed", label: "Failed Payments", icon: XCircle, accent: "red" },
    { id: "refunds", label: "Refunds", icon: RotateCcw, accent: "red" },
    { id: "currency", label: "Currency Breakdown", icon: Globe, accent: "blue" },
    { id: "tax", label: "Tax / VAT Summary", icon: FileText, accent: "teal" },
  ),
  documents: tabs(
    { id: "all", label: "All Documents", icon: FileText },
    { id: "invoices", label: "Invoices", icon: FileText },
    { id: "receipts", label: "Receipts", icon: FileCheck },
    { id: "payment-confirmations", label: "Payment Confirmations", icon: CreditCard },
    { id: "measurements", label: "Measurement Documents", icon: Ruler },
    { id: "tailor-notes", label: "Tailor Notes", icon: ClipboardList },
    { id: "delivery", label: "Delivery Documents", icon: Truck },
    { id: "uploaded", label: "Uploaded Files", icon: Archive },
    { id: "missing", label: "Missing Documents", icon: AlertTriangle },
  ),
  "exchange-rate": tabs(
    { id: "current", label: "Current Rates", icon: DollarSign },
    { id: "currencies", label: "Currency List", icon: Globe },
    { id: "manual", label: "Manual Rates", icon: Settings },
    { id: "sync-logs", label: "Auto Sync Logs", icon: History },
    { id: "history", label: "Rate History", icon: Calendar },
    { id: "conversion", label: "Conversion Settings", icon: RefreshCw },
  ),
  settings: tabs(
    { id: "general", label: "General Settings", icon: Settings },
    { id: "store", label: "Store Settings", icon: Store },
    { id: "email", label: "Email Settings", icon: Mail },
    { id: "payment", label: "Payment Settings", icon: CreditCard },
    { id: "delivery", label: "Delivery Settings", icon: Truck },
    { id: "currency", label: "Currency Settings", icon: Globe },
    { id: "tax", label: "Tax Settings", icon: FileText },
    { id: "notifications", label: "Notification Settings", icon: Bell },
    { id: "security", label: "Security Settings", icon: Shield },
    { id: "translation", label: "Translation Settings", icon: Globe },
  ),
  reports: tabs(
    { id: "overview", label: "Business Overview", icon: BarChart3 },
    { id: "sales", label: "Sales", icon: DollarSign },
    { id: "orders", label: "Orders", icon: ShoppingCart },
    { id: "customers", label: "Customers", icon: UserRound },
    { id: "product", label: "Clothes / Products", icon: Package },
    { id: "financial", label: "Payments", icon: CreditCard },
    { id: "delivery", label: "Delivery", icon: Truck },
    { id: "support", label: "Support", icon: Headphones },
  ),
  "support-inbox": tabs(),
  "activity-logs": tabs(
    { id: "all", label: "All Activity", icon: ScrollText },
    { id: "admin", label: "Admin Activity", icon: ShieldCheck },
    { id: "orders", label: "Order Activity", icon: ShoppingBag },
    { id: "payments", label: "Payment Activity", icon: CreditCard },
    { id: "products", label: "Product / Clothes Activity", icon: Package },
    { id: "customers", label: "Customer Activity", icon: Users },
    { id: "security", label: "Security Logs", icon: Lock },
    { id: "errors", label: "Error Logs", icon: AlertTriangle },
  ),
};

export const PAGE_META: Record<AdminPageId, Omit<AdminPageMeta, "tabs">> = {
  dashboard: {
    id: "dashboard",
    section: "Overview",
    icon: LayoutDashboard,
    title: "Dashboard",
    subtitle: "Monitor sales, orders, customers, products, payments, and alerts.",
    defaultTab: "overview",
  },
  employees: {
    id: "employees",
    section: "Users",
    icon: UsersRound,
    title: "Employees",
    subtitle: "Manage staff accounts, roles, activity, and performance.",
    defaultTab: "all",
  },
  customers: {
    id: "customers",
    section: "Users",
    icon: UserRound,
    title: "Customers",
    subtitle: "Manage customer accounts, orders, measurements, support history, and purchase behavior.",
    defaultTab: "all",
  },
  roles: {
    id: "roles",
    section: "Users",
    icon: ShieldCheck,
    title: "Roles & Permissions",
    subtitle: "Control admin access, permission groups, and security policies.",
    defaultTab: "roles",
  },
  products: {
    id: "products",
    section: "Catalog",
    icon: Package,
    title: "Clothes Inventory",
    subtitle: "Manage Habesha clothing items, stock, categories, images, and variants.",
    defaultTab: "all",
  },
  sections: {
    id: "sections",
    section: "Catalog",
    icon: FolderTree,
    title: "Sections",
    subtitle: "Organize clothing collections, homepage blocks, and menu sections.",
    defaultTab: "all",
  },
  orders: {
    id: "orders",
    section: "Operations",
    icon: ShoppingCart,
    title: "Orders",
    subtitle: "Track customer orders, tailoring status, payments, and delivery progress.",
    defaultTab: "all",
  },
  payments: {
    id: "payments",
    section: "Operations",
    icon: CreditCard,
    title: "Payments",
    subtitle: "Manage Stripe payments, QR/bank transfers, refunds, and verification.",
    defaultTab: "overview",
  },
  documents: {
    id: "documents",
    section: "Operations",
    icon: FileText,
    title: "Order Documents",
    subtitle: "Invoices, receipts, tailoring notes, measurement files, and delivery proofs.",
    defaultTab: "all",
  },
  "exchange-rate": {
    id: "exchange-rate",
    section: "Operations",
    icon: ArrowLeftRight,
    title: "Exchange Rate",
    subtitle: "Manage currencies, manual overrides, and conversion settings.",
    defaultTab: "current",
  },
  reports: {
    id: "reports",
    section: "Reports",
    icon: BarChart3,
    title: "Reports Center",
    subtitle: "Analyze business performance with dynamic reports and exports.",
    defaultTab: "overview",
  },
  "support-inbox": {
    id: "support-inbox",
    section: "System",
    icon: Headphones,
    title: "Support Inbox",
    subtitle: "Manage customer emails, support messages, complaints, order questions, payment issues, and replies from one place.",
    defaultTab: "all",
  },
  settings: {
    id: "settings",
    section: "System",
    icon: Settings,
    title: "Settings",
    subtitle: "Configure store, email, payment, delivery, currency, and security settings.",
    defaultTab: "general",
  },
  "activity-logs": {
    id: "activity-logs",
    section: "System",
    icon: ScrollText,
    title: "Activity Logs",
    subtitle: "Monitor admin actions, system events, security logs, and errors.",
    defaultTab: "all",
  },
};

export function getPageMeta(pageId: AdminPageId): AdminPageMeta {
  const meta = PAGE_META[pageId];
  return {
    ...meta,
    tabs: PAGE_TABS[pageId],
  };
}

export { adminNavigation as sidebarConfig } from "@/lib/dashboard-navigation";
