import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bell,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Eye,
  EyeOff,
  FileCheck,
  FileText,
  FolderTree,
  Globe,
  Headphones,
  History,
  Image,
  KeyRound,
  LayoutDashboard,
  List,
  Lock,
  Mail,
  MapPin,
  Package,
  Palette,
  RefreshCw,
  RotateCcw,
  Ruler,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Star,
  Store,
  Truck,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  XCircle,
} from "lucide-react";
import type { AdminPageId, AdminPageMeta, AdminTabConfig } from "./types";

function tabs(...items: AdminTabConfig[]): AdminTabConfig[] {
  return items;
}

export const PAGE_TABS: Record<AdminPageId, AdminTabConfig[]> = {
  dashboard: tabs(
    { id: "overview", label: "Overview", icon: LayoutDashboard },
    { id: "sales", label: "Sales", icon: DollarSign },
    { id: "orders", label: "Orders", icon: ShoppingCart },
    { id: "customers", label: "Customers", icon: UserRound },
    { id: "products", label: "Products", icon: Package },
    { id: "payments", label: "Payments", icon: CreditCard },
    { id: "delivery", label: "Delivery", icon: Truck },
    { id: "alerts", label: "Alerts", icon: Bell },
  ),
  employees: tabs(
    { id: "all", label: "All Employees", icon: UsersRound },
    { id: "active", label: "Active", icon: UserCheck },
    { id: "inactive", label: "Inactive", icon: UserRound },
    { id: "new", label: "New Employees", icon: UserPlus },
    { id: "access_pending", label: "Access Pending", icon: Lock },
    { id: "activity", label: "Activity", icon: Activity },
  ),
  customers: tabs(
    { id: "all", label: "All Customers", icon: Users },
    { id: "active", label: "Active", icon: UserCheck },
    { id: "inactive", label: "Inactive", icon: UserRound },
    { id: "new", label: "New Customers", icon: UserPlus },
    { id: "top", label: "Top Customers", icon: Star },
  ),
  roles: tabs(
    { id: "roles", label: "Roles", icon: Shield },
    { id: "permissions", label: "Permissions", icon: KeyRound },
    { id: "admins", label: "Admin Users", icon: ShieldCheck },
    { id: "security", label: "Security Logs", icon: ScrollText },
  ),
  products: tabs(
    { id: "all", label: "All Clothes", icon: Package },
    { id: "active", label: "Active Clothes", icon: CheckCircle2 },
    { id: "draft", label: "Draft Clothes", icon: FileText },
    { id: "low-stock", label: "Low Stock Clothes", icon: AlertTriangle, accent: "yellow" },
    { id: "out-of-stock", label: "Out of Stock", icon: XCircle, accent: "red" },
    { id: "best-selling", label: "Best Selling", icon: Star },
    { id: "categories", label: "Clothing Categories", icon: FolderTree },
    { id: "variants", label: "Size / Color Variants", icon: Palette },
    { id: "images", label: "Product Images", icon: Image },
    { id: "featured", label: "Featured Clothes", icon: Star },
  ),
  sections: tabs(
    { id: "all", label: "All Tribes", icon: List },
    { id: "active", label: "Active", icon: Eye },
    { id: "inactive", label: "Inactive", icon: EyeOff },
  ),
  orders: tabs(
    { id: "all", label: "All Orders", icon: ClipboardList },
    { id: "new", label: "New Orders", icon: ShoppingCart },
    { id: "pending", label: "Pending Orders", icon: Clock },
    { id: "processing", label: "Processing", icon: RefreshCw },
    { id: "tailoring", label: "Tailoring / Measurement", icon: Ruler },
    { id: "ready", label: "Ready for Delivery", icon: Package },
    { id: "delivered", label: "Delivered", icon: CheckCircle2 },
    { id: "cancelled", label: "Cancelled", icon: XCircle },
    { id: "returned", label: "Returned", icon: RotateCcw },
    { id: "custom", label: "Custom Clothing Orders", icon: Ruler },
  ),
  "returns-refunds": tabs(
    { id: "all", label: "All Requests", icon: RotateCcw, accent: "orange" },
    { id: "pending", label: "Pending Review", icon: Clock, accent: "yellow" },
    { id: "approved", label: "Approved", icon: CheckCircle2, accent: "green" },
    { id: "refunded", label: "Refunded", icon: CreditCard, accent: "red" },
    { id: "rejected", label: "Rejected", icon: XCircle, accent: "red" },
  ),
  "shipping-delivery": tabs(
    { id: "all", label: "All Deliveries", icon: Truck, accent: "orange" },
    { id: "preparing", label: "Preparing", icon: Package, accent: "yellow" },
    { id: "shipped", label: "Shipped", icon: Truck, accent: "blue" },
    { id: "out_for_delivery", label: "Out for Delivery", icon: MapPin, accent: "purple" },
    { id: "delivered", label: "Delivered", icon: CheckCircle2, accent: "green" },
    { id: "failed", label: "Failed", icon: XCircle, accent: "red" },
  ),
  payments: tabs(
    { id: "overview", label: "Overview", icon: LayoutDashboard, accent: "blue" },
    { id: "all", label: "All Payments", icon: Wallet, accent: "blue" },
    { id: "stripe", label: "Stripe Payments", icon: CreditCard, accent: "purple" },
    { id: "bank", label: "Bank Transfer / QR", icon: Banknote, accent: "green" },
    { id: "pending", label: "Pending Verification", icon: Clock, accent: "yellow" },
    { id: "failed", label: "Failed Payments", icon: XCircle, accent: "red" },
    { id: "refunds", label: "Refunds", icon: RotateCcw, accent: "red" },
    { id: "currency", label: "Currency Breakdown", icon: Globe, accent: "blue" },
    { id: "tax", label: "Tax / VAT Summary", icon: FileText, accent: "teal" },
  ),
  transactions: tabs(
    { id: "all", label: "All Transactions", icon: Wallet, accent: "green" },
    { id: "paid", label: "Paid", icon: CheckCircle2, accent: "green" },
    { id: "pending", label: "Pending", icon: Clock, accent: "yellow" },
    { id: "failed", label: "Failed", icon: XCircle, accent: "red" },
    { id: "refunded", label: "Refunded", icon: RotateCcw, accent: "red" },
  ),
  "customer-credits": tabs(
    { id: "customers", label: "Customer Balances", icon: Wallet, accent: "green" },
    { id: "ledger", label: "Credit Ledger", icon: History, accent: "blue" },
    { id: "rules", label: "Credit Rules", icon: Settings, accent: "teal" },
  ),
  "profit-costs": tabs(
    { id: "summary", label: "All Profit Summary", icon: Wallet, accent: "green" },
    { id: "catalog", label: "Product Profit Details", icon: Package, accent: "blue" },
  ),
  "coupons-discounts": tabs(
    { id: "discounts", label: "Discounts", icon: DollarSign, accent: "green" },
    { id: "coupons", label: "Coupons", icon: ShoppingBag, accent: "green" },
  ),
  documents: tabs(
    { id: "all", label: "All Orders", icon: FileText },
    { id: "needs_review", label: "Needs Review", icon: AlertTriangle },
    { id: "payment_proof", label: "Payment Proofs", icon: CreditCard },
    { id: "pickup", label: "In-Store Pickup", icon: MapPin },
    { id: "mailed", label: "Mailed / Shipped", icon: Truck },
    { id: "complete", label: "Docs Complete", icon: FileCheck },
  ),
  "uploaded-designs": tabs(
    { id: "all", label: "Custom Designs", icon: Image },
    { id: "pending_review", label: "Pending Review", icon: Clock },
    { id: "awaiting_payment", label: "Awaiting Payment", icon: CreditCard },
    { id: "completed_request", label: "Completed Requests", icon: CheckCircle2 },
    { id: "rejected", label: "Declined", icon: XCircle },
  ),
  "exchange-rate": tabs(
    { id: "current", label: "Current Rates", icon: DollarSign },
    { id: "currencies", label: "Currency List", icon: Globe },
    { id: "manual", label: "Manual Rates", icon: Settings },
    { id: "sync-logs", label: "Auto Sync Logs", icon: History },
    { id: "history", label: "Rate History", icon: Calendar },
    { id: "conversion", label: "Conversion Settings", icon: RefreshCw },
  ),
  settings: tabs(
    { id: "profile", label: "Profile Settings", icon: Settings },
    { id: "pricing", label: "Global Pricing Rules", icon: DollarSign },
  ),
  "backup-restore": tabs(
    { id: "overview", label: "Overview", icon: LayoutDashboard },
    { id: "backups", label: "Backup Activity", icon: FileCheck },
    { id: "restore", label: "Restore Activity", icon: RotateCcw },
    { id: "failures", label: "Failures", icon: AlertTriangle },
  ),
  reports: tabs(
    { id: "overview", label: "Business Overview", icon: BarChart3 },
    { id: "sales", label: "Sales", icon: DollarSign },
    { id: "orders", label: "Orders", icon: ShoppingCart },
    { id: "customers", label: "Customers", icon: UserRound },
    { id: "product", label: "Clothes / Products", icon: Package },
    { id: "financial", label: "Payments", icon: CreditCard },
    { id: "delivery", label: "Delivery", icon: Truck },
    { id: "support", label: "Support", icon: Headphones },
  ),
  "support-inbox": tabs(),
  "activity-logs": tabs(
    { id: "all", label: "All Activity", icon: ScrollText },
    { id: "admin", label: "Admin Activity", icon: ShieldCheck },
    { id: "orders", label: "Order Activity", icon: ShoppingBag },
    { id: "payments", label: "Payment Activity", icon: CreditCard },
    { id: "products", label: "Product / Clothes Activity", icon: Package },
    { id: "customers", label: "Customer Activity", icon: Users },
    { id: "security", label: "Security Logs", icon: Lock },
    { id: "errors", label: "Error Logs", icon: AlertTriangle },
  ),
  alerts: tabs(
    { id: "all", label: "All Notifications", icon: Bell },
    { id: "new", label: "New", icon: AlertTriangle },
    { id: "read", label: "Read", icon: CheckCircle2 },
    { id: "archived", label: "Archived", icon: FileText },
  ),
};

export const PAGE_META: Record<AdminPageId, Omit<AdminPageMeta, "tabs">> = {
  dashboard: {
    id: "dashboard",
    section: "Overview",
    icon: LayoutDashboard,
    title: "Dashboard",
    subtitle: "Monitor sales, orders, customers, products, payments, and alerts.",
    defaultTab: "overview",
  },
  employees: {
    id: "employees",
    section: "Users",
    icon: UsersRound,
    title: "Employees",
    subtitle: "Manage staff accounts, roles, activity, and performance.",
    defaultTab: "all",
  },
  customers: {
    id: "customers",
    section: "Users",
    icon: UserRound,
    title: "Customers",
    subtitle: "Manage customer accounts, orders, measurements, support history, and purchase behavior.",
    defaultTab: "all",
  },
  roles: {
    id: "roles",
    section: "Users",
    icon: ShieldCheck,
    title: "Roles & Permissions",
    subtitle: "Control admin access, permission groups, and security policies.",
    defaultTab: "roles",
  },
  products: {
    id: "products",
    section: "Catalog",
    icon: Package,
    title: "Clothes Inventory",
    subtitle: "Manage Habesha clothing items, stock, categories, images, and variants.",
    defaultTab: "all",
  },
  sections: {
    id: "sections",
    section: "Catalog",
    icon: FolderTree,
    title: "Tribes & Regions",
    subtitle: "Organize homepage tribes, regions, and menu visibility.",
    defaultTab: "all",
  },
  orders: {
    id: "orders",
    section: "Operations",
    icon: ShoppingCart,
    title: "Orders",
    subtitle: "Track customer orders, tailoring status, payments, and delivery progress.",
    defaultTab: "all",
  },
  "returns-refunds": {
    id: "returns-refunds",
    section: "Operations",
    icon: RotateCcw,
    title: "Returns & Refunds",
    subtitle: "Review return requests, refund status, rejected claims, and completed refunds from live order data.",
    defaultTab: "pending",
  },
  "shipping-delivery": {
    id: "shipping-delivery",
    section: "Operations",
    icon: Truck,
    title: "Shipping & Delivery",
    subtitle: "Track delivery readiness, shipped orders, final delivery state, and failed fulfillment follow-up.",
    defaultTab: "all",
  },
  payments: {
    id: "payments",
    section: "Operations",
    icon: CreditCard,
    title: "Payments",
    subtitle: "Manage Stripe payments, QR/bank transfers, refunds, and verification.",
    defaultTab: "overview",
  },
  transactions: {
    id: "transactions",
    section: "Finance",
    icon: Wallet,
    title: "Transactions",
    subtitle: "Monitor payment transactions, settlement state, failed attempts, and refunded order payments.",
    defaultTab: "all",
  },
  "customer-credits": {
    id: "customer-credits",
    section: "Finance",
    icon: Wallet,
    title: "Customer Credit Ledger",
    subtitle: "Track automatic bonus credits, customer balances, and credit usage history.",
    defaultTab: "customers",
  },
  "profit-costs": {
    id: "profit-costs",
    section: "Finance",
    icon: Wallet,
    title: "Profit & Cost Analysis",
    subtitle: "System-calculated product revenue, production cost, net profit, and margin.",
    defaultTab: "summary",
  },
  "coupons-discounts": {
    id: "coupons-discounts",
    section: "Finance",
    icon: DollarSign,
    title: "Promotions",
    subtitle: "Create and manage product discounts and checkout coupon codes.",
    defaultTab: "discounts",
  },
  documents: {
    id: "documents",
    section: "Operations",
    icon: FileText,
    title: "Order Documents",
    subtitle: "Invoices, receipts, tailoring notes, measurement files, and delivery proofs.",
    defaultTab: "all",
  },
  "uploaded-designs": {
    id: "uploaded-designs",
    section: "Catalog",
    icon: Image,
    title: "Custom Designs",
    subtitle: "Review customer custom design requests and approve/reject before checkout.",
    defaultTab: "all",
  },
  "exchange-rate": {
    id: "exchange-rate",
    section: "Operations",
    icon: ArrowLeftRight,
    title: "Exchange Rate",
    subtitle: "Manage currencies, manual overrides, and conversion settings.",
    defaultTab: "current",
  },
  reports: {
    id: "reports",
    section: "Reports",
    icon: BarChart3,
    title: "Reports Center",
    subtitle: "Analyze business performance with dynamic reports and exports.",
    defaultTab: "overview",
  },
  "support-inbox": {
    id: "support-inbox",
    section: "System",
    icon: Headphones,
    title: "Support Inbox",
    subtitle: "Manage customer emails, support messages, complaints, order questions, payment issues, and replies from one place.",
    defaultTab: "all",
  },
  settings: {
    id: "settings",
    section: "System",
    icon: Settings,
    title: "Settings",
    subtitle: "Manage your profile and universal product pricing rules.",
    defaultTab: "profile",
  },
  "backup-restore": {
    id: "backup-restore",
    section: "System",
    icon: FileCheck,
    title: "Backup & Restore",
    subtitle: "Review backup readiness, restore history, and system recovery audit events.",
    defaultTab: "overview",
  },
  "activity-logs": {
    id: "activity-logs",
    section: "System",
    icon: ScrollText,
    title: "Activity Logs",
    subtitle: "Monitor admin actions, system events, security logs, and errors.",
    defaultTab: "all",
  },
  alerts: {
    id: "alerts",
    section: "System",
    icon: Bell,
    title: "Alerts",
    subtitle: "Review actionable admin notifications that need attention.",
    defaultTab: "new",
  },
};

export function getPageMeta(pageId: AdminPageId): AdminPageMeta {
  const meta = PAGE_META[pageId];
  return {
    ...meta,
    tabs: PAGE_TABS[pageId],
  };
}

export { adminNavigation as sidebarConfig } from "@/lib/dashboard-navigation";
